[dependencies]

[package]
  cjc-version = "0.53.18"
  compile-option = ""
  description = "L25"
  link-option = ""
  name = "L25"
  output-type = "executable"
  src-dir = ""
  target-dir = ""
  version = "0.0.1"
  package-configuration = {}

[ffi.c] 
  cstruct.path = "."